### ISSUE TITLE
ERROR [14/15],ERROR[15/15]

### ISSUE THREAD

**Issue by Whiplash-18** [SimmerChan/KG-demo-for-movie#26]
在执行docker build -t kbqa:V0.1 . 命令时出现的两个错误，有人可以解答吗？谢谢各位！
=> ERROR [14/15] RUN /usr/local/bin/pip3.6 install -r requirements.txt -i https://pypi.tun  71.6s
------
 > [14/15] RUN /usr/local/bin/pip3.6 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ && rm -rf ~/.cache/pip:
#18 0.947 Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
#18 6.284 Collecting jieba>=0.39
#18 6.890   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c6/cb/18eeb235f833b726522d7ebed54f2278ce28ba9438e3135ab0278d9792a2/jieba-0.42.1.tar.gz (19.2 MB)
#18 17.51 Collecting refo==0.13
#18 19.05   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/51/b1/fe3af8c96aa634a9502bec5622aadc2e27880843a1da2c5869435772b075/REfO-0.13.tar.gz (12 kB)
#18 19.88 Collecting SPARQLWrapper==1.8.5
#18 19.93   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/00/9b/443fbe06996c080ee9c1f01b04e2f683b2b07e149905f33a2397ee3b80a2/SPARQLWrapper-1.8.5-py3-none-any.whl (26 kB)
#18 20.05 Collecting streamlit==0.66.0
#18 20.13   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/73/f2/03193332b9ced126141f095a7b0b75a1a5f43665aa1e4eb58d7cc0f69977/streamlit-0.66.0-py2.py3-none-any.whl (7.2 MB)
#18 38.05 Collecting altair>=3.2.0
#18 38.23   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/01/55/0bb2226e34f21fa549c3f4557b4f154a5632f61132a969da17c95ca8eab9/altair-4.1.0-py3-none-any.whl (727 kB)
#18 39.73 Collecting astor
#18 40.05   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c3/88/97eef84f48fa04fbd6750e62dcceafba6c63c81b7ac1420856c8dcc0a3f9/astor-0.8.1-py2.py3-none-any.whl (27 kB)
#18 40.23 Collecting base58
#18 40.33   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/3c/03/58572025c77b9e6027155b272a1b96298e711cd4f95c24967f7137ab0c4b/base58-2.0.1-py3-none-any.whl (4.3 kB)
#18 40.34 Collecting blinker
#18 40.40   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/1b/51/e2a9f3b757eb802f61dc1f2b09c8c99f6eb01cf06416c0671253536517b6/blinker-1.4.tar.gz (111 kB)
#18 40.69 Collecting boto3
#18 41.02   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/5c/8f/93e490e99c25bebbc79f762448866acf4b942ea6666423ac308c2aedb800/boto3-1.16.29-py2.py3-none-any.whl (129 kB)
#18 41.46   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b7/df/6c160e21a5caa800de16f2aa859b92671623118b4d124639aeab06876c06/boto3-1.16.28-py2.py3-none-any.whl (129 kB)
#18 42.15 Collecting botocore>=1.13.44
#18 42.33   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ac/e0/966b82eb9eab5fe36e80bcbbfda0d3f49cdd9ec896ebe9edb9824f896cd7/botocore-1.19.28-py2.py3-none-any.whl (7.0 MB)
#18 46.55 Collecting cachetools>=4.0
#18 46.59   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/cd/5c/f3aa86b6d5482f3051b433c7616668a9b96fbe49a622210e2c9781938a5c/cachetools-4.1.1-py3-none-any.whl (10 kB)
[+] Building 459.8s (19/22)
 => [internal] load build definition from Dockerfile                                                                                                   0.1so
 => => transferring dockerfile: 1.18kB                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                        0.0sy
 => [internal] load metadata for docker.io/library/ubuntu:16.04                                                                                        3.0s
 => [1/18] FROM docker.io/library/ubuntu:16.04@sha256:3355b6e4ba1b12071ba5fe9742042a2f10b257c908fbdfac81912a16eb463879                                 0.0s
 => [internal] load build context                                                                                                                      0.1s-
 => => transferring context: 39.49kB                                                                                                                   0.1s
 => CACHED [2/18] RUN sed -i 's#http://archive.ubuntu.com/#http://mirrors.tuna.tsinghua.edu.cn/#' /etc/apt/sources.list                                0.0s
 => CACHED [3/18] RUN apt-get update                                                                                                                   0.0s-
 => [4/18] RUN apt-get install dos2unix                                                                                                                1.9s
 => [5/18] RUN apt-get -y install vim                                                                                                                 25.6s
 => [6/18] RUN apt-get -y install python-software-properties                                                                                          74.5s
 => [7/18] RUN apt-get -y install software-properties-common                                                                                           4.6s
 => [8/18] RUN add-apt-repository ppa:deadsnakes/ppa -y                                                                                                5.8s
 => [9/18] RUN apt-get update                                                                                                                          8.7s
 => [10/18] RUN apt-get -y install python3.6                                                                                                          55.5s
 => [11/18] RUN apt-get -y install python3.6-dev                                                                                                      73.2s
 => [12/18] RUN apt-get -y install default-jdk                                                                                                       114.5s
 => [13/18] ADD . /kbqa                                                                                                                               13.1s
 => [14/18] WORKDIR /kbqa                                                                                                                              0.3s
 => ERROR [15/18] RUN /usr/bin/python3.6 get-pip.py                                                                                                   78.7s
------
 > [15/18] RUN /usr/bin/python3.6 get-pip.py:
#19 3.478 Collecting pip
#19 5.143   Downloading pip-20.3.1-py2.py3-none-any.whl (1.5 MB)
#19 78.66 ERROR: Exception:
#19 78.66 Traceback (most recent call last):
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
#19 78.66     yieldding https://pypi.tuna.tsinghua.edu.cn/packages/87/86/753182c9085ba4936c0076269a571613387cdb77ae2bf537448bfd63472c/numpy-1.19.4-cp36-cp36
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_vendor/urllib3/response.py", line 507, in read
#19 78.66     data = self._fp.read(amt) if not fp_closed else b""
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
#19 78.66     data = self.__fp.read(amt).6/dist-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
#19 78.66   File "/usr/lib/python3.6/http/client.py", line 463, in read
#19 78.66     n = self.readinto(b)ython3.6/dist-packages/pip/_vendor/urllib3/response.py", line 519, in read
#19 78.66   File "/usr/lib/python3.6/http/client.py", line 507, in readinto
#19 78.66     n = self.fp.readinto(b)on3.6/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
#19 78.66   File "/usr/lib/python3.6/socket.py", line 586, in readinto
#19 78.66     return self._sock.recv_into(b)ient.py", line 463, in read
#19 78.66   File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
#19 78.66     return self.read(nbytes, buffer)nt.py", line 507, in readinto
#19 78.66   File "/usr/lib/python3.6/ssl.py", line 874, in read
#19 78.66     return self._sslobj.read(len, buffer)ne 586, in readinto
#19 78.66   File "/usr/lib/python3.6/ssl.py", line 631, in read
#19 78.66     v = self._sslobj.read(len, buffer)ne 1012, in recv_into
#19 78.66 socket.timeout: The read operation timed out
#19 78.66   File "/usr/lib/python3.6/ssl.py", line 874, in read
#19 78.66 During handling of the above exception, another exception occurred:
#19 78.66   File "/usr/lib/python3.6/ssl.py", line 631, in read
#19 78.66 Traceback (most recent call last):fer)
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_internal/cli/base_command.py", line 186, in _main
#19 78.66     status = self.run(options, args)
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_internal/commands/install.py", line 331, in run
#19 78.66     resolver.resolve(requirement_set)
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_internal/legacy_resolve.py", line 177, in resolve
#19 78.66     discovered_reqs.extend(self._resolve_one(requirement_set, req))se_command.py", line 224, in _main
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
#19 78.66     abstract_dist = self._get_abstract_dist_for(req_to_install)i/req_command.py", line 180, in wrapper
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
#19 78.66     abstract_dist = self.preparer.prepare_linked_requirement(req)ands/install.py", line 321, in run
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
#19 78.66     hashes=hashes,/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_internal/operations/prepare.py", line 287, in unpack_url
#19 78.66     hashes=hashes,/lib/python3.6/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_internal/operations/prepare.py", line 159, in unpack_http_url
#19 78.66     link, downloader, temp_dir.path, hashesges/pip/_vendor/resolvelib/resolvers.py", line 339, in resolve
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_internal/operations/prepare.py", line 303, in _download_http_url
#19 78.66     for chunk in download.chunks:dist-packages/pip/_vendor/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_internal/utils/ui.py", line 160, in iter
#19 78.66     for x in it:al/lib/python3.6/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 198, in _get_criteria_to_update
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_internal/network/utils.py", line 39, in response_chunks
#19 78.66     decode_content=False,thon3.6/dist-packages/pip/_internal/resolution/resolvelib/provider.py", line 102, in get_dependencies
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_vendor/urllib3/response.py", line 564, in stream
#19 78.66     data = self.read(amt=amt, decode_content=decode_content)/resolution/resolvelib/provider.py", line 101, in <listcomp>
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_vendor/urllib3/response.py", line 529, in read
#19 78.66     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)ion/resolvelib/candidates.py", line 252, in iter_dependencies
#19 78.66   File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
#19 78.66     self.gen.throw(type, value, traceback)ages/pip/_internal/resolution/resolvelib/candidates.py", line 234, in dist
#19 78.66   File "/tmp/tmphlld1n8u/pip.zip/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
#19 78.66     raise ReadTimeoutError(self._pool, None, "Read timed out.")solution/resolvelib/candidates.py", line 221, in _prepare
#19 78.66 pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
------.51   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 314, in _prepare_distribution
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c /usr/bin/python3.6 get-pip.py]: runc did not terminate sucessfullyFile "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
#18 71.51     return self._prepare_linked_requirement(req, parallel_builds)
F:\Repository\testgit\KG-demo-for-movie-master>-packages/pip/_internal/operations/prepare.py", line 505, in _prepare_linked_requirement
#18 71.51     self.download_dir, hashes,
#18 71.51   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 257, in unpack_url
#18 71.51     hashes=hashes,
#18 71.51   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 130, in get_http_url
#18 71.51     from_path, content_type = download(link, temp_dir.path)
#18 71.51   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/network/download.py", line 163, in __call__
#18 71.51     for chunk in chunks:
#18 71.51   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/progress_bars.py", line 168, in iter
#18 71.51     for x in it:
#18 71.51   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/network/utils.py", line 88, in response_chunks
#18 71.51     decode_content=False,
#18 71.51   File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/urllib3/response.py", line 576, in stream
#18 71.51     data = self.read(amt=amt, decode_content=decode_content)
#18 71.51   File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/urllib3/response.py", line 541, in read
#18 71.51     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
#18 71.51   File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
#18 71.51     self.gen.throw(type, value, traceback)
#18 71.51   File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
#18 71.51     raise ReadTimeoutError(self._pool, None, "Read timed out.")
#18 71.51 pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out.
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c /usr/local/bin/pip3.6 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ && rm -rf ~/.cache/pip]: runc did not terminate sucessfully

**Comment by sshimii** [comment]
我是把pip3.6直接改成了pip，然后多试几次，就好了

**Comment by m871543713** [comment]
我多试了几次还是不行

**Comment by SimmerChan** [comment]
我已收到您的邮件，祝您生活愉快！

**Comment by m871543713** [comment]
请问楼主解决了吗？我出现了同样的问题

**Comment by LydiaCai1203** [comment]
@monkeycode-ai 看看这个

**Comment by MonkeyCode-AI** [comment]
> 我是 [MonkeyCode AI 编程助手](https://monkeycode-ai.com/)，你可以在  GitHub 任意仓库的任意 Issue 或 PR 中 at @monkeycode-ai 来呼唤我。

> 任务执行细节请参考: [ad4fa8ae-a8c5-11f0-9478-ee6ce69b85f1](https://monkeycode-ai.com/task?id=ad4fa8ae-a8c5-11f0-9478-ee6ce69b85f1)

根据分析，Issue #26 报告的Docker构建错误主要由以下两个原因导致：

1. 在Dockerfile中执行`RUN /usr/bin/python3.6 get-pip.py`时出现网络超时错误，这可能是因为网络连接问题或pip源不稳定导致的。
2. 在安装requirements.txt中的依赖包时同样出现网络超时错误，特别是在下载某些包（如numpy）时。

这两个问题都与网络连接和pip源的稳定性有关。

建议解决方案：
1. 更新Dockerfile中的pip安装方式，使用更稳定的pip源或增加重试机制。
2. 考虑使用pip的离线安装包或预先下载依赖包到本地。
3. 更新Dockerfile以使用更现代的基础镜像和Python版本，因为Ubuntu 16.04和Python 3.6已经相对陈旧。

由于此问题需要修改Dockerfile和可能的依赖管理策略，建议创建一个Pull Request来解决这个问题。
