### ISSUE TITLE
想请教一下我运行最新的这个版本，为什么运行query_main文件报错了

### ISSUE THREAD

**Issue by 1191452002** [SimmerChan/KG-demo-for-movie#30]
Traceback (most recent call last):
  File "D:/Graduation project experiment/KG-demo-for-movie-master/kg_demo_movie/KB_query/query_main.py", line 65, in <module>
    ans = qa_interface.answer(question)
  File "D:/Graduation project experiment/KG-demo-for-movie-master/kg_demo_movie/KB_query/query_main.py", line 33, in answer
    result = self.fuseki.get_sparql_result(my_query)
  File "D:\Graduation project experiment\KG-demo-for-movie-master\kg_demo_movie\KB_query\jena_sparql_endpoint.py", line 28, in get_sparql_result
    return self.sparql_conn.query().convert()
  File "D:\Python\lib\site-packages\SPARQLWrapper\Wrapper.py", line 1107, in query
    return QueryResult(self._query())
  File "D:\Python\lib\site-packages\SPARQLWrapper\Wrapper.py", line 1073, in _query
    response = urlopener(request)
  File "D:\Python\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Python\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "D:\Python\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "D:\Python\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "D:\Python\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "D:\Python\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "D:\Python\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "D:\Python\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "D:\Python\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

请教一下大家谢谢了

**Comment by LydiaCai1203** [comment]
@monkeycode-ai 看看这个问题

**Comment by MonkeyCode-AI** [comment]
> 我是 [MonkeyCode AI 编程助手](https://monkeycode-ai.com/)，你可以在  GitHub 任意仓库的任意 Issue 或 PR 中 at @monkeycode-ai 来呼唤我。

> 任务执行细节请参考: [9279a80a-a973-11f0-b6c3-ee6ce69b85f1](https://monkeycode-ai.com/task?id=9279a80a-a973-11f0-b6c3-ee6ce69b85f1)

## Issue分析结果

### 问题根本原因

用户在运行`query_main.py`文件时报错："http.client.RemoteDisconnected: Remote end closed connection without response"，这表明：

1. **Fuseki服务未运行**: 错误日志显示连接被远程端关闭而没有任何响应，这通常是因为Apache Jena Fuseki服务器没有启动。

2. **配置路径问题**: 在`jena_sparql_endpoint.py`中，默认的endpoint_url为'http://0.0.0.0:3030/kg_demo_movie/query'，但如果Fuseki服务没有正确启动或端口配置不同，就会导致连接失败。

### 解决方案

#### 必须步骤：

1. **启动Fuseki服务**: 用户需要先启动Apache Jena Fuseki服务器才能运行查询程序。
   ```bash
   cd /workspace/jena/apache-jena-fuseki-3.5.0
   ./fuseki-server
   ```

2. **确认配置文件路径**: 当前的`fuseki_conf.ttl`文件中有硬编码路径`/kbqa/jena/apache-jena-fuseki-3.5.0/run/databases/`，这在本地环境中不存在。需要修改这些路径为实际存在的路径。

3. **确保TDB数据存在**: 查看README发现需要使用`tdbloader`命令加载数据文件`kg_demo_movie.nt`到TDB数据库中。

#### 推荐改进：

1. **添加服务状态检查**: 在`query_main.py`中添加对Fuseki服务是否可访问的检查逻辑。

2. **完善文档**: 在README中增加关于如何正确启动Fuseki服务以及如何验证服务正常运行的说明。

### 具体操作步骤：

1. 修改`/workspace/jena/apache-jena-fuseki-3.5.0/run/configuration/fuseki_conf.ttl`中的路径为实际路径：
   ```
   # 修改以下行
   ja:content [ja:externalContent <file:///workspace/ontology.ttl> ] ;
   # 和
   ja:rulesFrom <file:///workspace/rules.ttl> ;
   # 以及
   tdb:location "/workspace/jena/tdb" ;
   ```

2. 创建TDB目录并加载数据：
   ```bash
   mkdir -p /workspace/jena/tdb
   /workspace/jena/apache-jena-3.5.0/bin/tdbloader --loc="/workspace/jena/tdb" "/workspace/kg_demo_movie.nt"
   ```

3. 启动Fuseki服务：
   ```bash
   cd /workspace/jena/apache-jena-fuseki-3.5.0
   ./fuseki-server
   ```

4. 在另一个终端运行查询程序：
   ```bash
   python3 /workspace/kg_demo_movie/KB_query/query_main.py
   ```
